// Code generated by protoc-gen-go. DO NOT EDIT.
// source: patricia.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Node struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Next                 []string `protobuf:"bytes,3,rep,name=Next,proto3" json:"Next,omitempty"`
	Val                  string   `protobuf:"bytes,4,opt,name=Val,proto3" json:"Val,omitempty"`
	Count                int32    `protobuf:"varint,5,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_patricia_09cb4e9b1065fad8, []int{0}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Node) GetNext() []string {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *Node) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

func (m *Node) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*Node)(nil), "pb.Node")
}

func init() { proto.RegisterFile("patricia.proto", fileDescriptor_patricia_09cb4e9b1065fad8) }

var fileDescriptor_patricia_09cb4e9b1065fad8 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x48, 0x2c, 0x29,
	0xca, 0x4c, 0xce, 0x4c, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x4a,
	0xe3, 0x62, 0xf1, 0xcb, 0x4f, 0x49, 0x15, 0xe2, 0xe3, 0x62, 0xf2, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0x60, 0x0e, 0x02, 0xb2, 0x84, 0x84, 0xb8, 0x58, 0x3c, 0x12, 0x8b, 0x33, 0x24, 0x98, 0x80,
	0x22, 0x9c, 0x41, 0x60, 0x36, 0x48, 0xcc, 0x2f, 0xb5, 0xa2, 0x44, 0x82, 0x59, 0x81, 0x19, 0x24,
	0x06, 0x62, 0x0b, 0x09, 0x70, 0x31, 0x87, 0x25, 0xe6, 0x48, 0xb0, 0x80, 0x95, 0x81, 0x98, 0x42,
	0x22, 0x5c, 0xac, 0xce, 0xf9, 0xa5, 0x79, 0x25, 0x12, 0xac, 0x40, 0x31, 0xd6, 0x20, 0x08, 0x27,
	0x89, 0x0d, 0x6c, 0xa5, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x33, 0x76, 0x19, 0x84, 0x00,
	0x00, 0x00,
}
