// Code generated by protoc-gen-go. DO NOT EDIT.
// source: patricia.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Node struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Next                 []string `protobuf:"bytes,2,rep,name=Next,proto3" json:"Next,omitempty"`
	Val                  string   `protobuf:"bytes,3,opt,name=Val,proto3" json:"Val,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_patricia_ddcb70b908ba780f, []int{0}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Node) GetNext() []string {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *Node) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

func (m *Node) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Tree struct {
	Root                 *Node    `protobuf:"bytes,1,opt,name=Root,proto3" json:"Root,omitempty"`
	List                 []*Node  `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tree) Reset()         { *m = Tree{} }
func (m *Tree) String() string { return proto.CompactTextString(m) }
func (*Tree) ProtoMessage()    {}
func (*Tree) Descriptor() ([]byte, []int) {
	return fileDescriptor_patricia_ddcb70b908ba780f, []int{1}
}
func (m *Tree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tree.Unmarshal(m, b)
}
func (m *Tree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tree.Marshal(b, m, deterministic)
}
func (dst *Tree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tree.Merge(dst, src)
}
func (m *Tree) XXX_Size() int {
	return xxx_messageInfo_Tree.Size(m)
}
func (m *Tree) XXX_DiscardUnknown() {
	xxx_messageInfo_Tree.DiscardUnknown(m)
}

var xxx_messageInfo_Tree proto.InternalMessageInfo

func (m *Tree) GetRoot() *Node {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *Tree) GetList() []*Node {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "pb.Node")
	proto.RegisterType((*Tree)(nil), "pb.Tree")
}

func init() { proto.RegisterFile("patricia.proto", fileDescriptor_patricia_ddcb70b908ba780f) }

var fileDescriptor_patricia_ddcb70b908ba780f = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x48, 0x2c, 0x29,
	0xca, 0x4c, 0xce, 0x4c, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x0a,
	0xe3, 0x62, 0xf1, 0xcb, 0x4f, 0x49, 0x15, 0x12, 0xe2, 0x62, 0xf1, 0x48, 0x2c, 0xce, 0x90, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x7e, 0xa9, 0x15, 0x25, 0x12, 0x4c, 0x0a,
	0xcc, 0x20, 0x31, 0x10, 0x5b, 0x48, 0x80, 0x8b, 0x39, 0x2c, 0x31, 0x47, 0x82, 0x19, 0xac, 0x0c,
	0xc4, 0x14, 0x12, 0xe1, 0x62, 0x75, 0xce, 0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x01, 0x8a, 0xb1, 0x06,
	0x41, 0x38, 0x4a, 0x4e, 0x5c, 0x2c, 0x21, 0x45, 0xa9, 0xa9, 0x42, 0x32, 0x5c, 0x2c, 0x41, 0xf9,
	0xf9, 0x25, 0x60, 0x73, 0xb9, 0x8d, 0x38, 0xf4, 0x0a, 0x92, 0xf4, 0x40, 0xf6, 0x05, 0x81, 0x45,
	0x41, 0xb2, 0x3e, 0x99, 0xc5, 0x10, 0x1b, 0x50, 0x64, 0x41, 0xa2, 0x49, 0x6c, 0x60, 0x67, 0x1a,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x77, 0xbe, 0x3b, 0xd1, 0xb8, 0x00, 0x00, 0x00,
}
